### ISSUE TITLE
Alpine image for minimal size

### ISSUE THREAD

**Issue by pksunkara** [klaemo/docker-couchdb#101]
I would love to have this for couchDB. Currently, the images sizes are too big.

**Comment by klaemo** [comment]
Yeah that would be lovely. Would you want to work on this?

**Comment by pksunkara** [comment]
I would love to but unfortunately I don't have experience in installing couchDB. From what I understand from the other files, it doesn't look as straight forward as possible.

**Comment by klaemo** [comment]
yeah, I think I looked into it a while back, but couldn't get erlang to run or something. Don't quite remember

**Comment by pksunkara** [comment]
There is an erlang alpine image now.

**Comment by apihlaja** [comment]
@pksunkara yeah, img size is huge (over 350 MB) but it seems erlang is pretty space hungry: building erlang under alpine linux (using [kerl](https://github.com/kerl/kerl)) results ~150 MB release dir. So I'm curious to know how much space can be actually saved with alpine linux.

I did some work on [building couchdb2 in alpine](https://gist.github.com/apihlaja/48f3e8128ecf7a5b22447472b3334940) (copypasta, not script/Dockerfile). It compiles, I didnt test it further (yet).

**Comment by apihlaja** [comment]
Just a little update... It seems trivial to bring features on par with Debian image. That's not the problem. But I have some issues which effectively stalled my work. I don't really see it viable to ship official Alpine CouchDB anytime soon.

### mozjs185

The root of all issues: [mozjs185](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Releases/1.8.5) is from 2011. No upstream patches since then. GCC 6 can't compile original codebase.

### Alpine releases

Coincidentally, the latest Alpine (3.5) ships with GCC 6 & co. When looking [Alpine´s release policy](https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases), they offer only 2 year maintenance cycle. Targeting to old version is not option there.

### mozjs from Debian / Fedora

Both Debian and Fedora have custom patched versions, they ship with GCC 6 so they have patch for that too. I glanced both, I got a bit confused and even suspicious how their patching works. I tried to track down how Debian build tools do it but I didn't find the answer. It may be that Busybox's patch & co are missing some option. I thought I should open Stackoverflow question about it but haven't done so yet. Anyway, I couldn't find clean way to apply their patches. I could do it manually one by one but I'd prefer to know what I'm mimicking if doing so.

### Replace mozjs?

At some point, I tracked down why CouchDB is still using ancient version of SpiderMonkey. And is there any plans to upgrade / replace it? Node.js version is even mentioned in documentation somewhere, but if I'm right, the idea was shut down around 2013. Also, I remember python version mentioned somewhere.

Surprisingly, just a day or two later, @dmunch's [couch-chakra](https://github.com/dmunch/couch-chakra) popped up. Since my alpine build wont be stable/prod-ready anytime soon, I might as well try to build it with chakra version. I don't know how realistic that plan that is, but I think I'll try at some point. I glanced chakra-core docs/src, and I didn't notice any immediate showstopper.

**Comment by dmunch** [comment]
While I don't wont to dis-encourage you to replace mozjs I want to stress that couch-chakra really is in its very early stages. ChakraCore itself had its first release with full JIT support on Linux/Mac in December 2016 so nobody really knows how it behaves in the wild. As for couch-chakra, the only thing it ever ran was the test-suite for the query server protocol, I actually never ran it for processing a "real-life" view function. 

I would of course be all for driving couch-chakra further and would be more than happy to see it used in the wild and would voluntarily give a helping hand in building, debugging and doing whatever it needs to get it to work. I just want to stress that, by choosing this route, you're potentially going down a deep rabbit hole transporting you light years form the the initial issue :)

**Comment by apihlaja** [comment]
@dmunch  Your [readme](https://github.com/dmunch/couch-chakra#motivation) makes things pretty clear but good that it's said explicitly here too: My previous post means, I abandoned idea of Alpine based CouchDB 2.0 image. I'm not going to complete it as it is. If I continue that project, it will be something really, really, experimental. Or I simply wait.

Debian & RH/Fedora teams are maintaining legacy mozjs package: if you want to use current CouchDB, use their package. That's what I will be doing..

**Comment by klaemo** [comment]
Wow, this has been super interesting to follow 😊 I really hope CouchDB is going to start using a more modern js runtime or just drop the concept of a view server and make everything declarable via mango or something similar. 

Anyways, I'm going to close this issue as an Alpine image doesn't seem possible.
