### ISSUE TITLE
Contribute this to Apache CouchDB?

### ISSUE THREAD

**Issue by janl** [klaemo/docker-couchdb#22]
@klaemo would you be up for contributing this to Apache CouchDB proper, so we don’t have to maintain our own Dockerfile? Development could continue as usual, just on apache/couchdb instead of here.

**Comment by kxepal** [comment]
or we could create apache/couchdb-docker repository as well to keep container for 1.x and have separate release cycles. But in any case I'm +1 on this (:

**Comment by janl** [comment]
Does `Dockerfile` have to live on the top level? If not, we can do a sub-repo on our end. If yes, we can also import the 1.x version into our 1.x.x branch

**Comment by ngbinh** [comment]
:+1:

**Comment by klaemo** [comment]
I have no problem donating this to Apache CouchDB. Does this mean migrating to git.couchdb.org and JIRA, though? because that'd be... :cry: I'd prefer apache/docker-couchdb on github, because I want to keep the barrier to entry low.

@janl the Dockerfiles can live anywhere, but there are some restrictions with docker hub's automated build system pertaining to tags/versions. 

Also, once the migration is done, we can try to get the docker image promoted to an official image on docker hub. That way couchdb will be on par with other databases in that regard. 
How do you propose going forward?

**Comment by janl** [comment]
Yay, this is good news :)

The main repo for all Apache stuff is git.apache.org/*, but all of this is mirrored to github.com/apache/* and you can run Pull Requests against that as usual (just no issues or merge button).

So for this, it would mean either apache/couchdb (if we put the Dockerfile into the main, top-level repo) or apache/couchdb-docker if it should get its own repo.

Since you are the maintainer, you get to pick :)

One thing to consider: from 2.0 (current master) onwards, people check out apache/couchdb and then run `./configure` which in turn fetches all the other couchdb-* repos that are required to stand up CouchDB. So if you wanted to to run CouchDB in Docker, you’d have to fetch couchdb-docker on your own. If you are used to fetching the main repo, having the Dockerfile in there might be preferable. Or we leave a note in there, for people to go loo in couchdb-docker. OR you’d have to run `./configure` before you could get to the Dockerfile at `src/couchdb-docker`, but then you’d also wait for all other modules to fetch which you don’t necessarily need.

That said, if you download a regular CouchDB release tarball, `src/couchdb-docker` would already exist, so less of an issue there.

Aaanyway, happy to chat in person / IRC to clear things up, but ultimately, this is your contribution and we should do what feels right to you :)

I’m +1 on making the image official :)

**Comment by klaemo** [comment]
From wednesday on I'll have more free time to get this rolling.
We should definitely have a chat about the details :)

**Comment by klaemo** [comment]
@criloz since you've contributed to this repo, I have to ask: are you willing to sign the CLA? https://www.apache.org/licenses/icla.txt

**Comment by criloz** [comment]
@klaemo sure where can I send the documents.?

**Comment by janl** [comment]
@criloz secretary@apache.org

**Comment by janl** [comment]
@criloz did you have a chance to send the file(s)? I couldn’t find anything under `criloz`. If you used a real name, could you tell me? (privately at jan@apache.org if you prefer), so I can match it up with the ASF records.

After some more revisiting, I think we only need the CLA from you, but not the grant. Sorry for the confusion.

**Comment by janl** [comment]
Update: The CouchDB dev community has accepted docker-couchdb as a contribution, now we have to get some paperwork done, that you don’t have to concern yourselves with. I’ll keep you posted.

**Comment by klaemo** [comment]
:heart:

**Comment by klaemo** [comment]
@janl just checking in, what's the status here?

**Comment by janl** [comment]
thanks for the nudge! :)

**Comment by janl** [comment]
https://github.com/klaemo/docker-couchdb/pull/27

**Comment by janl** [comment]
Ok, I started the paperwork, we should be good to go in 72 hours :)

**Comment by klaemo** [comment]
This time it was me slacking, due to being busy. I just responded to the corresponding email. We're on our way! Slowly, but surely :D

**Comment by kxepal** [comment]
\o/

**Comment by klaemo** [comment]
I'm ready to rock! ;) What's next?

**Comment by snowch** [comment]
@janl / @klaemo - what's the status with moving this into the apache repo?  There's some stuff that can be done to reduce the size of the 2.0-dev image, but it probably makes sense to submit the patches directly to the apache repo?  https://github.com/klaemo/docker-couchdb/issues/32

**Comment by klaemo** [comment]
@snowch I'm waiting for more information from the CouchDB folks. It's kind of confusing currently.

**Comment by janl** [comment]
wait, who’s waiting for who? :D

**Comment by klaemo** [comment]
We're in some kind of limbo. Partly because I didn't get around to migrating everything properly, partly because Apache and Github aren't the best of friends. :D

There is `apache/couchdb-docker` which mirrors apache git. Unfortunately there is no straightforward way to migrate this repo to the apache on, so I push to both (that's what @jo is doing with `nano` as well afaik). Also apache/* repos don't allow github issues. So, that's pretty much a no-go for me.

I've opened a PR on apache/couchdb to update the Dockerfile there. Need to finish this.
I'm currently favoring a 2-tier approach:

- `apache/couchdb/Dockerfile`: for development and testing only (getting the needed deps, building couchdb locally from source etc)
- `klaemo/docker-couchdb` and/or ` apache/couchdb-docker`: for running 1.x, 2.x and master quickly. should all be available on docker hub for quick downloadable images (is already the case, except for master). Ideally, I get them to accept it as an official image.

So, yeah...it's mainly on me to get my act together ;-) But if you have any advice on the repo migration I'd be happy :)

**Comment by kxepal** [comment]
IIRC @robertkowalski experimented with complete Github repo transfer to ASF with stars, issues and everything. Not sure how this ended, however.

**Comment by robertkowalski** [comment]
still waiting for the new github api that asf infra needs / wants

**Comment by klaemo** [comment]
I just submitted CouchDB to the `official-images` repo. If the review goes well, CouchDB will have an official Docker image soon (like pretty much every database out there). That means users will be able to `docker run couchdb` instead of `docker run klaemo/couchdb`.

You can check the status [here](https://github.com/docker-library/official-images/pull/1288).

I submitted version `1.6.1` as well as for `2.0-dev`. That should make it pretty easy for people to give `2.0` a spin. Of course, I'll add future releases as they come out.

Next step: get the development `Dockerfile` in `apache/couchdb` sorted out.

**Comment by janl** [comment]
Update: ASF infra is not yet ready to import GitHub repos wholesale, and keeping GitHub issues is another thing that needs some work. We’ll continue this process, once ASF infra is ready.

**Comment by klaemo** [comment]
Status update from my side:
- this repo acts as official docker image source for now
- PouchDB started using our docker images in their CI setup :tada: 
- the PR for the dev docker setup is in good shape now imho (https://github.com/apache/couchdb/pull/340)
- the official docker image PR is still waiting for review (https://github.com/docker-library/official-images/pull/1288)

**Comment by klaemo** [comment]
Actually, this is done 🎉
