### ISSUE TITLE
GET request to /_log returns badmatch (eof)

### ISSUE THREAD

**Issue by zemirco** [klaemo/docker-couchdb#47]
Right now a GET request to [http://localhost:5984/_log](http://localhost:5984/_log) returns

```json
{"error":"badmatch","reason":"eof"}
```

That's because the logs are written to [dev/null](https://github.com/klaemo/docker-couchdb/blob/master/1.6.1/Dockerfile#L94). I assume it has something to do with Docker logging. The logs in Docker work fine. 

Any idea / plans to make them both work? I mean logs in Docker and logs in the web? Or is that on purpose and we should ignore the logs through the website?

**Comment by klaemo** [comment]
In the process of making this image an official image, the docker hub maintainers suggested only logging to `stdout` https://github.com/docker-library/official-images/pull/1288#issuecomment-173604247. I didn't think of the `_log` endpoint :( It makes sense to only log to `stdout` because otherwise you would need to setup something like logrotate inside of the container.

You can however change the log target to a file/directory and then host mount it as a volume and do whatever you want with it.

**Comment by zemirco** [comment]
Cheers! I was just wondering if there is something wrong on my side. I can live with logs only from Docker.

**Comment by kxepal** [comment]
@zemirco FYI /_log will be removed in 2.0 and eventually we have to deprecate it now.
