### ISSUE TITLE
[Feature Request] Provide Image with Clouseau / Fulltext Search

### ISSUE THREAD

**Issue by janl** [klaemo/docker-couchdb#48]
It’d be cool to have a build of 2.0 that includes the Cloudant Fulltext Search setup described in https://cloudant.com/blog/enable-full-text-search-in-apache-couchdb/

Note, this is not a request to make the 2.0 image to include this, but a new image that is 2.0 + the full text stuff :)

**Comment by klaemo** [comment]
:+1: Sounds good. This will only be possible once there's an official alpha/beta/RC release of 2.0, though.

**Comment by janl** [comment]
Couldn’t we make it like the `2.0-dev-docs` sub-directory here?

**Comment by kxepal** [comment]
For 1.x you can include https://github.com/rnewson/couchdb-lucene plugin. IIRC it provides the same API.

**Comment by janl** [comment]
@kxepal good thinking!

**Comment by klaemo** [comment]
@janl we can make it a subdirectory here, but it can't be included in the official images for now, because they don't allow `git clone`s. See https://github.com/docker-library/official-images/pull/1288#issuecomment-173365497

It would still be available as something like `klaemo/couchdb:2.0-fulltext`

**Comment by klaemo** [comment]
Regarding `couchdb-lucence`: I think from a docker perspective it would make sense to make it its own container and document how to link the CouchDB container with the `couchdb-lucene` one.
It just doesn't feel right to run CouchDB, the JVM and Lucene in the same container. The same goes for the 2.0 version.

**Comment by iboware** [comment]
Hi,
I am just wondering about if it is possible to integrate Closeau / Fulltext Search with CouchDB 1.6 image. I know maybe this is not the right  place to ask but would be wonderful if it is possible, because I need it for my production environment.

**Comment by klaemo** [comment]
@iboware you can run https://github.com/rnewson/couchdb-lucene in a docker container and connect it with our couchdb one. If you explore this please let me know how it worked out or if you have questions.

**Comment by iboware** [comment]
@klaemo thanks for your quick response. I actually tried that but what I need is an API similar to Cloudant. Currently we are using Cloudant on our application but it is a bit expensive for us, because we have a few customers. On the other side Cloudant went offline for nearly one day last week and we have waited in a desperate situation. This is why I want to build a couchdb server with the current fulltext search and mango query features of Cloudant. I tried 2.0 with docker and manually building. It works well, but I don't know how reliable is 2.0 for the production so I am just looking a solution working with 1.6, a more stable one.

**Comment by klaemo** [comment]
Hm... @janl what are his options? afaik couchdb-lucene is for 1.x, Clouseau for 2.0, but 2.0 is not production ready, correct?

**Comment by klaemo** [comment]
FYI here is a WIP dockerized couchdb-lucene https://github.com/klaemo/docker-couchdb-lucene

**Comment by iboware** [comment]
Thanks, I have tried greenlizard/couchdb-lucene with 1.6, but I couldn't make it work. Do I need to link your version of couchdb-lucene with couchdb container?
For those who are looking for a dockerized image of couchdb2 fulltext search enabled https://hub.docker.com/r/ncheaz/couchdb/

**Comment by klaemo** [comment]
@iboware as far as I understand it you would have to link them both ways. CouchDB needs access to CouchDB Lucene and the other way around. I'm looking into it at the moment.

Thanks for the link :)

**Comment by klaemo** [comment]
@iboware here is a working example of a dockerized couchdb-lucene https://github.com/klaemo/docker-couchdb-lucene/tree/master/example

**Comment by janl** [comment]
@klaemo you are correct, c-l is for 1.x and Clouseau is for 2.x only and CouchDB 2.x isn’t production ready yet.

@iboware I don’t know if it is an option for you, but my company might be able to help with this in the context of a professional engagement (https://neighbourhood.ie/couchdb-support for some info), feel free to get in touch any time: jan@neighbourhood.ie END_OF_COMMERCIAL

**Comment by iboware** [comment]
@klaemo Danke, I will try this if we decide to go with Couchdb 1.6. 

@janl Actually everything is an option, but I am not the one who decides about this matters. Currently waiting at least for 2.0 beta seems to be more logical. If we decide to get professional support about this subject, I will definitely get in touch with you.

**Comment by sam** [comment]
I could be wrong, but from looking at it, `couchdb-lucene` isn't compatible with the Cloudant Search API. Which makes it pretty niche. It's certainly not going to let people run a local development copy of their system deployed to Cloudant (unless I'm mistaken). Which is the goal when asking for this feature generally I think. I'm very happy with Cloudant's dedicated clusters, service, etc in general. But a local database for development would be great.

Ideally there'd be an image for CouchDB 2.0, based on the RC(s), that ran a single node for a development environment. ncheaz/couchdb comes close, but it still runs multiple nodes (I think; tried it yesterday) and is based on 2.0-alpha.

Since I work from a CPU/RAM limited 2015 Apple Macbook I'd be even happier to have a .dmg like the current 1.6.1 MacOS release (but for 2.0RC, with search enabled). Docker doesn't really do anything for my local development when my production target is Cloudant. Not to sound ungrateful. It's the next best thing to an official search-enabled release for now!

Either way I've waited a very long time for CouchDB+Search so I'm very excited about 2.0!

**Comment by klaemo** [comment]
AFAIK `couchdb-lucene` is not meant to be compatible with Cloudant Search. It is a different approach to full text indexing. `Clouseau` is the Clouding thing and CouchDB 2.0 compatible, but there is no docker version yet. I don't know when or if I'll make a docker image for this, though.
But if anyone is interested in contributing one...feel free :D

**Comment by sam** [comment]
@klaemo Right. I just meant to clarify (poorly) that the discussion around `couchdb-lucene` is a bit off-topic in a request for an image integrating Closeau. I imagine you're asking for Closeau because there's a good chance you already have an app written for it. You can't really just substitute one for the other. (Not trying to be the comment police or anything, people can discuss whatever they like, it's just not all that relevant for people who've developed apps against Cloudant, which I imagine is the audience for this request.)

If I knew how to Docker I might contribute. But I don't. So for now I'll just run my own non-Docker installation. Either way the work here is much appreciated!

**Comment by ronag** [comment]
https://github.com/ncheaz/cloudant-search

**Comment by ronag** [comment]
https://hub.docker.com/r/ibmcom/cloudant-developer/

**Comment by timmak** [comment]
Anyone had any luck with this?

**Comment by dmunch** [comment]
Just stumbled over this issue and realized that that's actually what I did a couple of weeks ago. 

What I did:
- Build a container with CouchDb built from source with the Dreyfus patches applied (https://github.com/dmunch/docker-couchdb/tree/master/2.0-dreyfus)
- Build a container for clouseau  (https://github.com/dmunch/docker-clouseau)
- Linked them via Docker compose (https://github.com/dmunch/docker-clouseau/blob/master/docker-compose.yml)

**Comment by garrensmith** [comment]
@dmunch a PR would be great.

**Comment by garrensmith** [comment]
Kamino closed and cloned this issue to apache/couchdb-docker

**Comment by garrensmith** [comment]
This is moved to https://github.com/apache/couchdb-docker/issues/8
